spring:
  application:
    name: SecureApp
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    password: root
    username: root
  jpa:
    hibernate:
      # create new DB when we start app and drop it when we stop the app
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
# shouldn't be here, instead we can store it in .env file
jwt:
  secret:
    key: 34624e6f726151396e6b416e653675577a48675661366f794941414776326234